[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
sqlx = {version = "0.8.3", features = ["runtime-tokio-native-tls", "sqlite"]}
tokio = {version = "1.43.0", features = ["macros", "full", "rt-multi-thread"]}
